spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/quizzick-user-service
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123456789}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
minio:
  endpoint: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:quizzick-user-service}
server:
  port: 11001
  servlet:
    context-path: /user
api-path:
  user-controller: /v1/users